### ISSUE TITLE
开启时候介绍的界面

### ISSUE THREAD

**Issue by rabbitcdn** [moegirlwiki/MoegirliOS#42]
- 欢迎
- 翻页方法
- 黑幕查看方法
- 图片保存方法
- 编辑功能
- 结束

**Comment by Illvili** [comment]
第一次显示 / 设置重置提示信息 这种么

**Comment by masterchan** [comment]
@Illvili  不太明白。我想弄的就是功能简介这样子。

**Comment by Illvili** [comment]
之前的版本简介只在第一次开启应用没有刷新的时候显示，后期再想看就不知道怎么看了。
所以这个是不是可以在第一次开启的时候显示，然后后期还能再找到。

**Comment by masterchan** [comment]
下次再设置里面弄一下
